### ISSUE TITLE
How to calculate hash for FirmwareUpgradeManager?

### ISSUE THREAD

**Issue by sjmerelglobus** [NordicSemiconductor/IOS-nRF-Connect-Device-Manager#195]
The FirmwareUpgradeManager.start() method now takes a hash parameter, but it's not explained in the README what kind of hash  is expected or how best to calculate it.

**Comment by philips77** [comment]
FYI: https://github.com/NordicSemiconductor/IOS-nRF-Connect-Device-Manager/pull/183

**Comment by nysander** [comment]
thanks but this should be somewhere documented

**Comment by philips77** [comment]
Right.

@dinesharjani, why is the has given as a separate parameter? For the sake of SUIT files? They also have the hash inside.

**Comment by dinesharjani** [comment]
@nysander you are correct. I hope I can get to it today.

As for why, it's because since nRF Connect uses this API, I found that making the hash "magic" made everything more complicated. Also, you can see how the hash should be calculated in the Example app for now. But yes, I should fix the README.

**Comment by nysander** [comment]
thanks
